---
- name: Run User setup role
  hosts: all
  become: yes
  become_method: sudo
  connection: ssh
  vars_files:
    - "./roles/java-app/vars/main.yml"
    - "./java-app-setup.yml"     
#  vars:
#    user_home: /home/{{ deploy_user }}
#    deploy_dir: "{{ user_home }}/deploy"
  roles:
    - java-kill-app
